server:
  port: 8081

spring:
  application:
    name: library

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library?useSSL=false
    username: root
    password: 111111

  redis:
    host: 192.168.93.20
    password: 123456
  mail:
    default-encoding: utf-8
    host: smtp.163.com
    username: 13450144906@163.com
    password: LMLBAOSKGFYCEQRA


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cbz.librarymanagementsystem.entity
  global-config:
    db-config:
      table-prefix: tb_
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl